services:
  mysql:
    image: mysql:8.4
    container_name: order-workflow-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: order_workflow
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
